pipeline {
  agent any

  environment {
    BRANCH_NAME = "${env.GIT_BRANCH}".replaceAll(".*/", "")
  }

  stages {
    stage('Deploy FE') {
      steps {
        script {
          def changed = sh(script: "git diff --name-only HEAD~1", returnStdout: true).trim()

          // if (!changed.contains("Stalk_FE/")) {
          //   echo "🟡 FE 디렉토리 변경 없음 → 배포 생략"
          //   return
          // }

          def isProd = BRANCH_NAME == 'master'
          def COMPOSE_FILE = isProd ? 'docker-compose.prod.yml' : 'docker-compose.dev.yml'

          sh """
            echo "🚀 FE docker-compose 실행 중..."
            docker compose -f ${COMPOSE_FILE} up -d --build stalk-fe
          """
        }
      }
    }
    
    stage('Deploy nginx') {
       steps {
          sh 'docker compose -f docker-compose.dev.yml up -d --build nginx stalk-fe-dev stalk-be-dev'
        }
    }
  }
}
