pipeline {
  agent any

  environment {
    BRANCH_NAME = "${env.GIT_BRANCH}".replaceAll(".*/", "")
  }

  stages {
    stage('Deploy FE') {
      steps {
        script {
          def changed = sh(script: "git diff --name-only HEAD~1", returnStdout: true).trim()

          // 필요하다면 FE 변경 여부로 배포 스킵 가능
          // if (!changed.contains("Stalk_FE/")) {
          //   echo "🟡 FE 디렉토리 변경 없음 → 배포 생략"
          //   return
          // }

          def isProd = BRANCH_NAME == 'master'
          def COMPOSE_FILE = isProd ? 'docker-compose.prod.yml' : 'docker-compose.dev.yml'

          sh """
            echo "🚀 FE docker-compose 실행 중 (${COMPOSE_FILE})..."
            docker compose -f ${COMPOSE_FILE} up -d --build stalk-fe
          """
        }
      }
    }
    
    stage('Deploy nginx') {
      steps {
        script {
          def isProd = BRANCH_NAME == 'master'
          def COMPOSE_FILE = isProd ? 'docker-compose.prod.yml' : 'docker-compose.dev.yml'

          sh """
            echo "🗑️ 기존 nginx 컨테이너 정리 (${COMPOSE_FILE})..."
            docker compose -f ${COMPOSE_FILE} rm -sf nginx || true

            echo "🛡️ nginx docker-compose 실행 중 (${COMPOSE_FILE})..."
            docker compose -f ${COMPOSE_FILE} up -d --no-deps nginx
          """
        }
      }
    }
  }
}
