pipeline {
  agent any

  environment {
    BRANCH_NAME = "${env.GIT_BRANCH}".replaceAll(".*/", "")
  }

  stages {
    stage('Deploy FE') {
      steps {
        script {

          def isProd = BRANCH_NAME == 'master'
          def COMPOSE_FILE = isProd ? 'docker-compose.prod.yml' : 'docker-compose.dev.yml'

          sh """
            echo "🚀 FE docker-compose 실행 중..."
            docker compose -f ${COMPOSE_FILE} up -d --build stalk-fe
          """
        }
      }
    }
  }
}
