pipeline {
  agent any

  environment {
    DOCKER_IMAGE = "stalk-be:latest"
  }

  stages {
    stage('Build JAR') {
      steps {
        dir('stalk_BE') {
          sh './gradlew clean build'
        }
      }
    }

    stage('Docker Build & Run') {
      steps {
        dir('stalk_BE') {
          sh '''
            docker stop stalk-be || true
            docker rm stalk-be || true
            docker build -t $DOCKER_IMAGE .
            docker run -d -p 8080:8080 --name stalk-be $DOCKER_IMAGE
          '''
        }
      }
    }
  }
}
